services:
  - type: web
    name: keycloak
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: KC_DB_URL
        value: jdbc:postgresql://dpg-d21qnfvgi27c73e8un9g-a/pedagogie_db7
      - key: KC_DB_USERNAME
        value: pedagogie_db7_user
      - key: KC_DB_PASSWORD
        value: XfmWDdbkiXcBQhtbX8hQxDxfTQIXBtyD
      - key: KC_HOSTNAME
        value: ton-domaine-keycloak.onrender.com
      - key: KC_PROXY
        value: edge
